### PR TITLE
Cleanups to Sundials PR

### PR DESCRIPTION
**Pull request by mboes**
This PR makes a number of cleanups to https://github.com/albertoruiz/hmatrix/pull/255, plus simplifies the build instructions. Using Stack, the build instructions are now simply:

```
$ stack --nix build
```

I encourage you to have a look at each commit individually to see the kind of cleanups I performed.

I'll let you update the README as appropriate.

Other cleanups I haven't addressed:
- It should be made clearer that the `sundials` executable is just an example, e.g. by naming it `example-hmatrix-sundials`.
- Building examples should be made optional, e.g. using a flag, or moved to a separate Cabal package not uploaded to Hackage.

### CODE REVIEW

**Comment by mboes** [comment]
Also, putting the `c-sources` line in the example instead of in the library looks very suspicious to me. I think you need it in the library. In either case, listing these files in `extra-source-files` is redundant.

**Comment by mboes** [comment]
And having a module export a `odeSolve` vs `solveOde` pair of functions is unintuitive. Also, both these functions need Haddocks.

**Comment by idontgetoutmuch** [comment]
> And having a module export a odeSolve vs solveOde pair of functions is unintuitive. Also, both these functions need Haddocks.

Indeed - what's great about sundials is I can get it to tell me (in the case of RK at least) the exact Butcher Tableau and I plan to include it in the haddocks - watch this space.

**Comment by idontgetoutmuch** [comment]
WRT [copyright](https://github.com/idontgetoutmuch/hmatrix/pull/1/commits/69d6f852035260ad2fe85e5d1a9803e7fef7837d) I started this in my spare time - only some of it is paid so maybe joint copyright is better? I will ask Fred.

**Comment by mboes** [comment]
In that case yes, joint copyright.

>

**Comment by idontgetoutmuch** [comment]
Sadly that has broken my build - I have gone back to HEAD~1 for now and will try and fix this later

**Pull request merged**
